version: '3.8'

services:

  db_test:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${TEST_PG_USER}
      POSTGRES_PASSWORD: ${TEST_PG_PASS}
      POSTGRES_DB: ${TEST_PG_DB}
    ports:
      - "${TEST_PG_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 10s
      timeout: 5s
      retries: 5

  web_tests:
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TEST_PG_USER}
      POSTGRES_PASSWORD: ${TEST_PG_PASS}
      POSTGRES_HOST: db_test
      POSTGRES_PORT: ${TEST_PG_PORT}
      POSTGRES_DB: ${TEST_PG_DB}
      DRIVER: ${TEST_PG_DRIVER}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "
        export DATABASE_URL=postgresql://test:test@db_test:5432/test &&
        alembic upgrade head && 
        pytest test_tests.py       
      "

    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - db_test